### ISSUE TITLE
直接运行workflow报错

### ISSUE THREAD

**Issue by cardenluo** [11dogzi/Comfyui-ergouzi-samplers#1]
[rgthree] Using rgthree's optimized recursive execution.
!!! Exception during processing!!! not enough values to unpack (expected 5, got 3)
Traceback (most recent call last):
  File "F:\ComfyUI_Windows_portable\ComfyUI\execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\ComfyUI_Windows_portable\ComfyUI\execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\ComfyUI_Windows_portable\ComfyUI\custom_nodes\ComfyUI-0246\utils.py", line 381, in new_func
    res_value = old_func(*final_args, **kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\ComfyUI_Windows_portable\ComfyUI\execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\ComfyUI_Windows_portable\ComfyUI\custom_nodes\Comfyui-ergouzi-samplers\EGJBCHCYQ.py", line 244, in sample
    image, mask, crop_coords,bytx, byzz = self.mask_crop(image, mask, Region_Extension, Partial_size)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: not enough values to unpack (expected 5, got 3)

**Comment by 11dogzi** [comment]
Try manually applying the mask or send a screenshot of the entire interface

**Comment by cardenluo** [comment]
Oh , updated comfyui , it can run well.
